[phases.setup]
runtime = "php@8.1"

[phases.install]
cmds = [
    "composer install --ignore-platform-reqs",
    "npm install"
]

[phases.build]
cmds = [
    "php artisan optimize:clear",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan migrate --force",
    "php artisan storage:link"
]

[phases.start]
cmd = "php artisan serve --host=0.0.0.0 --port=8000"

